### ISSUE TITLE
Create a new user in GUI

### ISSUE THREAD

**Issue by jchmielewska** [eu-nebulous/gui#24]
We need a possibility to add a new user in GUI for Open Call participants. We want them to have access to our cluster but they need the separate user in GUI.

**Comment by jchmielewska** [comment]
We've got a feedback from the use case partners that they will need that feature too. If they could login as the specific user and only view their applications.

**Comment by vkefalas-exz** [comment]
created new users in cd env:

uc1_admin
uc2_admin
uc3_admin
uc4_admin
uc5_admin
uc6_admin

**Comment by robert-sanfeliu** [comment]
done
