### ISSUE TITLE
Cloud registration form not keeping value for "Region" field

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/gui#28]
On nebulous-cd, register a new cloud provider of type AWS, select the region from the dropdown, save the cloud provider. Go back to edit the provider, the list of selected regions is empty. Select the region again, save, edit again, now the region field is not empty.

![image](https://github.com/user-attachments/assets/06474751-7ffe-41c4-9add-342c752f9b6c)

**Comment by emadellaloggia** [comment]
install this
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive
