### ISSUE TITLE
403 when managing resources

### ISSUE THREAD

**Issue by Iqqdd99** [eu-nebulous/gui#31]
In the Resources section a `403. API | Access denied. Request failed with status code 403` error appears when trying to delete, view or save a change in the Resource editing form.

Environment:
Fresh NebulOuS installation with the latest images.

**Comment by vkefalas-exz** [comment]
Can you please outline the steps how initiate the nebulous installation in order to be able to replicate?

**Comment by vkefalas-exz** [comment]
@Iqqdd99 do you still face this issue?

**Comment by robert-sanfeliu** [comment]
Let's assume it has been fixed
