### ISSUE TITLE
Access CFSB from GUI

### ISSUE THREAD

**Issue by gregkoron** [eu-nebulous/gui#39]
A button that links GUI with Cloud Fog Service Broker should be created. Based on what is discussed in the past, CFSB expects a link in this form "https://cfsb.cd.nebulouscloud.eu/?app_id=123a&user_id=abc1".

**Comment by robert-sanfeliu** [comment]
Moving to Open project
https://openproject.nebulouscloud.eu/projects/nebulous-2nd-release-1/work_packages/770/activity
