### ISSUE TITLE
Problem definining AWS Resources

### ISSUE THREAD

**Issue by atsag** [eu-nebulous/gui#41]
As reported by one of our pilots:

When we try to define AWS resources on the NebulOuS GUI, we still receive the following "API | Network/Server Error" message, details are below:
![image](https://github.com/user-attachments/assets/7e6e84a7-2dc7-4c00-ab28-2720e703850c)

**Comment by fotisp** [comment]
@atsag this is a deployment issue, should be forwarded to the deployment team

**Comment by robert-sanfeliu** [comment]
It is now happening on PROD environment.
